update workflow  [skip ci]

diff --git a/.github/workflows/ephemeral_eks_cloudflare.yml b/.github/workflows/ephemeral_eks_cloudflare.yml
--- a/.github/workflows/ephemeral_eks_cloudflare.yml
+++ b/.github/workflows/ephemeral_eks_cloudflare.yml
@@ -434,9 +434,10 @@ jobs:
     name: deploy-alb
     runs-on: ubuntu-latest
     needs: [configure-variables, deploy-network, deploy-iam, deploy-cluster, configure-auth, install-lbc]
-    if: needs.configure-variables.outputs.deploy_alb == 'true' &&
-      always() && 
-      needs.configure-variables.result == 'success' && 
+    if: |
+      always() &&
+      needs.configure-variables.result == 'success' &&
+      needs.configure-variables.outputs.deploy_alb == 'true' &&
       (needs.deploy-network.result == 'success' || needs.deploy-network.result == 'skipped') &&
       needs.deploy-iam.result == 'success' &&
       needs.deploy-cluster.result == 'success' && needs.configure-auth.result == 'success' &&
@@ -503,6 +504,7 @@ jobs:
       projectname: ${{ needs.configure-variables.outputs.projectname }}
       vpc_id: ${{ needs.configure-variables.outputs.vpc_id }}
       TF_VAR_region: ${{ needs.configure-variables.outputs.region }}
+      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
     steps:
       - name: checkout-code
         uses: actions/checkout@v4
@@ -520,6 +522,14 @@ jobs:
         with:
           terraform_version: ${{ env.TF_VERSION }}
           terraform_wrapper: false
+
+      - name: Verify Cloudflare token
+        run: |
+         if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
+           echo "::error::CLOUDFLARE_API_TOKEN is empty in this job"; exit 1
+         fi
+         curl -sf -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
+         https://api.cloudflare.com/client/v4/user/tokens/verify    
 
       - name: Terraform Init
         working-directory: ./environments/dev/alb/eks-routing
@@ -642,7 +652,7 @@ jobs:
             --set app.name=${{ env.HELM_RELEASE_NAME }} \
             --set image.tag=${{ steps.get_image_tag.outputs.image_tag }} \
             --set environment=${{ env.ENVIRONMENT }} \
-            --set targetGroupBinding.targetGroupArn=${{ env.target_group_arn }}
+            --set targetGroupBinding.targetGroupArn=${{ env.target_group_arn }} \
             --timeout 10m \
             --wait \
             --debug || {
