add cluster rollback on failure

diff --git a/.github/workflows/ephemeral_infra.yaml b/.github/workflows/ephemeral_infra.yaml
--- a/.github/workflows/ephemeral_infra.yaml
+++ b/.github/workflows/ephemeral_infra.yaml
@@ -245,9 +245,19 @@ jobs:
           path: ./environments/${{ env.ENVIRONMENT }}/cluster/tfplan.json
           
       - name: Terraform Apply
+        id: tf_apply
         working-directory: ./environments/${{ env.ENVIRONMENT }}/cluster
         run: terraform apply -auto-approve tfplan
-      
+        continue-on-error: true
+
+      - name: Roll back on Failure
+        if: steps.tf_apply.outcome == 'failure'
+        working-directory: ./environments/${{ env.ENVIRONMENT }}/cluster
+        run: |
+          echo "Cluster deployment failed, rolling back changes"
+          terraform destroy -auto-approve  -input=tfplan
+          exit 1
+        
       - name: Verify Cluster Deployment
         working-directory: ./environments/${{ env.ENVIRONMENT }}/cluster
         run: |
